name: Test Python Package

permissions:
  contents: write
  packages: write

on:
  pull_request:
    branches:
      - main

jobs:
    test-python-package:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'

        - name: Build and Install Python package
          run: |
            python packaging/package_build.py
            pip install *.tar.gz

        - name: 
